
package ifs353.finex;
  import java.io.BufferedReader;
  import java.io.File;
  import java.io.FileReader;
  import java.io.FileWriter;
  import java.io.IOException;
  import java.io.PrintWriter;
  import javax.swing.JFileChooser;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *A GUI that translates a set of integer array indices into a string of Unicode 
 *arrow chars and displays the arrows.
 * @author Dakalo Makatu, Nov 2022
 */
public class Translator extends javax.swing.JFrame {
            private final JFileChooser jfc;
            private File f;
            private FileReader fr;
            private FileWriter fw;
            private BufferedReader buffer;
            private PrintWriter writer;
            
            private ArrowSymbols translate;
            String arrowResult = "";
           
            
            

    /**
     * Creates new form Translator
     */
    public Translator() {
        jfc = new JFileChooser();
        initComponents();
        setLocationRelativeTo(null);
        jfc.setCurrentDirectory(new File("C:\\myJava"));
        translate = new ArrowSymbols(); //creates an instance of the ArrowSymbols class.
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textPane = new javax.swing.JTextPane();
        arrows = new javax.swing.JButton();
        codes = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openfile = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Codes to Arrow Translator");

        textPane.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        jScrollPane1.setViewportView(textPane);

        arrows.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        arrows.setText("To Arrows");
        arrows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrowsActionPerformed(evt);
            }
        });

        codes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        codes.setText("To Codes");
        codes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codesActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        openfile.setText("Open File");
        openfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openfileActionPerformed(evt);
            }
        });
        jMenu1.add(openfile);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(arrows)
                .addGap(78, 78, 78)
                .addComponent(codes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                .addComponent(clear)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrows)
                    .addComponent(codes)
                    .addComponent(clear))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arrowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrowsActionPerformed
     String integers;
     String [] integerarray;
     int [] codes;
        
      integers = textPane.getText();  //Gets users string input from the Textpane
      integerarray = integers.split(" "); //Splits the string into various sub-strings 
      codes = new int [integerarray.length]; //Stores the String of integers into an array.
         
 
     try{
             
       for(int i = 0; i <integerarray.length; i++){ // Loops through the array
           codes [i] = Integer.parseInt(integerarray[i]); //Parses the string input as a integer
         }
       

      }catch (NumberFormatException e){ //catches a number format exception
              showMessageDialog(null,"NumberFormatException\n"+ e.getMessage(),"ERROR",
                  ERROR_MESSAGE);
      }

      
       arrowResult = translate.toArrowsString(codes);//Stores the arrow symbols into a String called ArrowResult
       textPane.setText(arrowResult); //Dispalys Arrow symbols onto the TextPane
    }//GEN-LAST:event_arrowsActionPerformed

    private void codesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codesActionPerformed
        char[] arrows;
        arrowResult = arrowResult.replaceAll("\\s", ""); //Finds single whitespace characters and replaces them with an empty string.
        
        arrows = arrowResult.toCharArray(); //Converts the string of Arrow symbols to their integer code sequence. 
        
        textPane.setText(translate.toIntegersString(arrows)); //Dispalys the integers onto the TextPane
    }//GEN-LAST:event_codesActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       
        textPane.setText(" ");  //Sets the textpane to empty. 
        
    }//GEN-LAST:event_clearActionPerformed

    private void openfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openfileActionPerformed
       //Opens up an "Open File" file chooser dialog.
        int returnVal = jfc.showOpenDialog(openfile); 
        String line;
         //Using a string builder inorder to display text folders when opened.
        StringBuilder sb = new StringBuilder();
         
         try {
             if (returnVal == JFileChooser.APPROVE_OPTION){
              textPane.setText("");     //Set to null string to prepare it for file text.
              f = jfc.getSelectedFile();   //Returns the selected file.
              fr = new FileReader(f);
              buffer = new BufferedReader(fr);
              
              while((line =buffer.readLine()) !=null){
                   sb.append(line);
                
              }
               
              textPane.setText(sb.toString());
              fr.close();
              buffer.close();
              textPane.setCaretPosition(0);
              
             } else if (returnVal == JFileChooser.CANCEL_OPTION){
                  //NO action
             } 
             } catch (IOException e){
                     showMessageDialog(jMenuBar1,e.getMessage(),
                             "Error!", ERROR_MESSAGE);
              
              }
                       
        
    }//GEN-LAST:event_openfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Translator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Translator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Translator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Translator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Translator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arrows;
    private javax.swing.JButton clear;
    private javax.swing.JButton codes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem openfile;
    private javax.swing.JTextPane textPane;
    // End of variables declaration//GEN-END:variables
}
